# Generated by Django 3.2.4 on 2021-06-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20201215_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='picture',
            field=models.ImageField(blank=True, default='image1.jpg', null=True, upload_to=''),
        ),
    ]
